### ISSUE TITLE
[Feature Request]: Mod Options integration

### ISSUE THREAD

**Issue by TkabRft** [Deaadman/adaptive-arsenal#1]
### Describe the Feature

Allow user to adjust some parameteres through Mod Options, for example:
1. Wind speed impact on bullet trajectory
2. Muzzle velocity
3. Drop-off range and amount
4. Skill level impact (some players may prefer to have similar effect at all skill levels)

### Benefit of the Feature

More customized and pleasant experience for players

**Comment by Deaadman** [comment]
I have thought about this before releasing this mod, however the issue I find with options like this is users adjusting the muzzle velocity to a speed where this mod essentially becomes ineffective. Not only that, users will have to re-adjust to the new bullet drop based on their settings.

**Comment by APSIndustries** [comment]
Is there an easy way to see the values set for the mod? It's unclear how close or not they are to reality. Obviously the game's default damage outputs for both the revolver and the rifle are wildly out of line with reality. A .44 magnum is considered a decent bear gun, and is good for close range hunting, and the .303 British is a full powered rifle cartridge easily capable of taking out everything except perhaps the moose and bear in a single body shot. 

I'm not saying your mod needs to be in line with reality (to the contrary, since the game itself takes significant liberties), but it would be nice to know what you set it to to see how it compares both to the base game and reality, so I don't go in assuming it is completely realistic and screw myself over.

**Comment by Deaadman** [comment]
> Is there an easy way to see the values set for the mod? It's unclear how close or not they are to reality. Obviously the game's default damage outputs for both the revolver and the rifle are wildly out of line with reality. A .44 magnum is considered a decent bear gun, and is good for close range hunting, and the .303 British is a full powered rifle cartridge easily capable of taking out everything except perhaps the moose and bear in a single body shot.
> 
> I'm not saying your mod needs to be in line with reality (to the contrary, since the game itself takes significant liberties), but it would be nice to know what you set it to to see how it compares both to the base game and reality, so I don't go in assuming it is completely realistic and screw myself over.

To see the values that I've set for the projectiles in terms of velocity and damage, they are all within [this](<https://github.com/Deaadman/AdaptiveArsenal/blob/release/Source/Components/ProjectileItem.cs>) class. However if you don't understand how to read code then it might be a bit challenging to understand how it all comes together.

For damage, the rifle has a base damage which slowly increases as your players rifle skill level increases - this damage is also multiplied by a multiplier depending on what limb you hit of an animal such as a bear or a wolf. This also applies to the revolver, however all revolver have static base damages and don't increase as your revolver skill level increases, so I've basically added that myself. These values haven't been altered at all for gameplay purposes, I'm just using the values Hinterland themselves have set.

In terms of muzzle velocity when firing for each weapon, I've set these all to a value that represents the **type** of weapon it is. If it's got a shorter barrel, then I've made the muzzle velocity shorter. These values are nowhere near reality, because in reality you wouldn't even see the bullet exit any weapon - let alone account for bullet drop from a target that is 200 - 300 meters away.

If you want the most realism, it'd be best to stay away from this mod - there is a reason Hinterland made bullets hit scan rather than projectiles, and it'd be because it's more realistic. I made this mod in order to challenge players that have been using weapons for a long time, and it's fairly easy to hit a target when you are used to hit scan.
